### ISSUE TITLE
Concurrent Modification Exception thrown

### ISSUE THREAD

**Issue by davetao** [contentful/vault#105]
Hi.

I am getting a very strange error all of a sudden where the requestSync action fails to complete and we are getting a java.util.ConcurrentModificationException

It looks like it is caused by Retrofit.

OnErrorThrowable$OnNextValue "rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit.client.Response.class"

OnError while emitting onNext value: retrofit.client.Response.class"

Is there a way to trace the source of this problem?

It was working fine last week. The only thing that has changed is the volume of localised content. Which is quite large.

**Comment by tomxor** [comment]
Can you please post the complete stacktrace?

**Comment by davetao** [comment]
I dont have the exact stacktrace you are looking for but i was able to evaluate the exception object thrown by the vault sync function.

![stacktrace](https://cloud.githubusercontent.com/assets/4438069/10784954/d1b53e6e-7d58-11e5-814c-59b3d9b38896.png)

![exception](https://cloud.githubusercontent.com/assets/4438069/10784964/d9acdaa0-7d58-11e5-857b-084ee8fd37c8.png)

**Comment by davetao** [comment]
It doesnt look like its caused by retrofit but a problem with the modifications of the threads

**Comment by tomxor** [comment]
If you call `error.printStackTrace()` inside your catch block it should be visible via LogCat.

**Comment by davetao** [comment]
It just gives me a `result=undefined` 

But I do have something in the evaluator with more information regarding our crash

![screen shot 2015-10-28 at 16 01 43](https://cloud.githubusercontent.com/assets/4438069/10794538/40537d3e-7d8d-11e5-8bce-5f73807157bb.png)

**Comment by davetao** [comment]
I am using the latest version of vault

**Comment by tomxor** [comment]
:+1: thanks! I'll look into it.

**Comment by tomxor** [comment]
This is an issue with the contentful.java SDK.

**Comment by tomxor** [comment]
@davetao you can now upgrade vault to 0.9.12 which should resolve the issue. Note that if you're using the contentful.java dependency transitively, it has been upgraded to 5.0.1 (major release), so make sure to go through the [CHANGELOG](https://github.com/contentful/contentful.java/blob/master/CHANGELOG.md).

**Comment by davetao** [comment]
Thank you so much. I shall test it once it jcenter repos are updated

**Comment by tomxor** [comment]
No problem, thanks again for the bug report.
