### ISSUE TITLE
What is vault_file_name.db ? Where to get it from?

### ISSUE THREAD

**Issue by ishandutta2007** [contentful/vault#112]
In seeding section I saw it being mentioned to put file "vault_file_name.db" in assets folder and then refer it while declaring space. But no where I found it mentioned what "vault_file_name.db" is and how to generate or download it ?

**Comment by mariobodemann** [comment]
Hey,

the `vault_file_name.db` is the database file, created by an android app. To retrieve it you need to seed the data from an debug android app and use something like

http://stackoverflow.com/questions/14714173/how-to-get-database-file-from-any-android-project-in-emulator-or-in-pc

to retrieve it.

We are thinking about an easier way of doing so, by potentially adding a gradle task to do this, but for now we don't have it on a road map.

**Comment by ishandutta2007** [comment]
For no seeding case what is the suggested solution ?
is there a synchronous way to sync then query ?
sync() is taking 500 milisec on my network but the problem is since it is asynchronous the query is getting fired before its completion and returning zero results so on first install the app has no data unless i somehow call sync again.

**Comment by ishandutta2007** [comment]
Ideally putting a static db file makes no sense for me, basically if a user downloads app today static file of today's data would make some sense but putting it in asset would mean I can seed with at best case as latest as the app release day's data.

**Comment by mariobodemann** [comment]
Exactly,

and what you would gain, is that your user already has `some` data while in the background the newest data is fetched ....

**Comment by mariobodemann** [comment]
Closing this issue, due to inactivity.
