### ISSUE TITLE
Using the Preview API

### ISSUE THREAD

**Issue by davetao** [contentful/vault#114]
Hi,

I was wondering if it possible to use the Preview API + key with this Vault library?

How do we use the Vault library using the preview api token?

Is it supported?

I am getting an exception even though there is a function in the CDAClient to use the preview API.

java.lang.UnsupportedOperationException: Syncing using a preview token is not supported. Please use a production token.

**Comment by mariobodemann** [comment]
Hey,

sadly our [Preview API does not support syncing](https://www.contentful.com/developers/docs/references/content-preview-api/#/introduction/preview-api-limitations). And since syncing is the base of how Vault works, Vault and preview do not work together.

Sorry for this bad news, but if you want, would you like to share your usecase, so maybe there is a different way of modeling the described behaviour ...

Greetings,
Mario

**Comment by mariobodemann** [comment]
Hey,

I just wanted to follow up with you: Did you find a different way of modelling your usecase?

Greetings,
Mario

**Comment by davetao** [comment]
Hi @mariobodemann 
So we cannot access draft content using the vault library?

**Comment by mariobodemann** [comment]
Hey,

so the short answer is it `depends`. You cannot have a `preview` token on `vault`. You could remodel your `ContentType` to contain a field `published` to differentiate those two cases in vault, and once you publish your entry, you would also need to change this field, potentially by using a `Webhook` from Contentful.

I will investigate on how to add the `sys` field to all vault objects, so you could query the published state, in some future point in time...

Mario

**Comment by mariobodemann** [comment]
Hey @davetao,

did you find my last suggestion suitable, or should we try and find another one together?

**Comment by davetao** [comment]
Hi @mariobodemann 

It would have been quite a large update to change the model and editorial flow to account for this feature.

At the moment, our alternative is to create a mirror on the space as a staging environment and publish all the content there.

Would you know if the tools provided under the contentful-space-sync library also mirrors the unpublished content?

https://github.com/contentful/contentful-space-sync

**Comment by mariobodemann** [comment]
Hey,

so confirming with the maintainer (@Khaledgarbaya) of the space-sync-tool: The tool allows you to sync everything™. The published and not published content will get copied over to the new space, so for me it feels like a viable option, for having a draft like state and a production ready state of the content.

Please let me know, on how you progress, if there is something more we can do...

Greetings,
Mario

**Comment by davetao** [comment]
Hi @mariobodemann 

Does that mean that I technically can access unpublished content using the vault library if that tool is using the synchronisation API?

**Comment by Khaledgarbaya** [comment]
Hi @davetao ,

Sorry for the confusion, the space-sync tool only synchronizes **published** content. Anything in Draft mode or any unpublished changes to a published Entry will not be synchronized. Acces draft can be done using the preview API which does not support syncing.

Best,
Khaled

**Comment by jgrife** [comment]
@mariobodemann @Khaledgarbaya, 
So, If we have an Android app using Vault and we want to preview a Contentful Space on an Android debug build before publishing it live to a Android release build, then the solution would be: Configure a new 'mirrored' Space for the Android debug build; sync the live Space to this mirrored Space; make changes and publish in mirrored Space; once satisfied, then sync the mirrored Space to the live Space.

Does the above sound correct? Please let me know if there is another way to do this?

Thanks
Jason

**Comment by mariobodemann** [comment]
Hey all, 

yes that is exactly the way I can see it working.

Greetings,
Mario
