### ISSUE TITLE
Hint about contenttype

### ISSUE THREAD

**Issue by BraunreutherA** [contentful/vault#119]
Hi there, 

I was struggling for some days why my stuff wasn't synced. The Problem was I wrote the contenttypes with an capital letter in the beginning, because it's displayed in the web interface of contentful. I think it would be a good idea to examine users of vault to have a look into the json preview and search for the contenttype.

Best 
Alex

**Comment by mariobodemann** [comment]
Hey,

thank you for this insight. We'll keep this in mind and think about how to make it more friction less. An alternative recommendation would be to take the [generator.java](https://github.com/contentful/generator.java) which generates the required class layout, directly based on your setup in Contentful.

Greetings,
Mario
