### ISSUE TITLE
How to use LIKE operator for fetching items

### ISSUE THREAD

**Issue by kzotin** [contentful/vault#124]
Hi,
I'm desperately trying to fetch all items whose Title contains MY_QUERY with vault + RxJava.

I've tried tons of variants, including:
`.observe(Guide.class).where("title LIKE '%?%'", "MY_QUERY").all()` 
`.observe(Guide.class).where("query", "MY_QUERY").all()` 

And many other options... Can you advise, please?

**Comment by mariobodemann** [comment]
Hey,

I'm currently not on my working machine, but from ontop of my head, I was wondering if you tried using the helper classes created by Vault (`ContentType$Fields.TITLE`, for a Vault generated class `ContentType`).

You would use it like:

```
.where( ContentType$Fields.TITLE + " LIKE '%?%'", "MY QUERY") 
```

Hope that helps ...
Mario

**Comment by kzotin** [comment]
Hi @mariobodemann,
Yes, I've used generated model field exactly the same way you suggested, and result is the same - 0 items are returned, even with request 
`.where(ContentType$Fields.TITLE + " LIKE '%'", "MY QUERY")`

The model is quite straightforward without any hacks

**Comment by kzotin** [comment]
Any advice how to search for items in different way would be appreciated :)

**Comment by mariobodemann** [comment]
Hey,

after digging some more through it, (See this nice [SO answer](https://stackoverflow.com/questions/9076561/android-sqlitedatabase-query-with-like))I found that the `%`s have to be part of the args parameter:

```
vault
  .observe(Person.class)
  .where(Person$Fields.NAME + " LIKE ?", "%mar%")
  .all()
// and so on
```
Using this where clause, I could get all the persons having mar in any case somewhere in the name.

Hope this helps you too,
Mario

**Comment by kzotin** [comment]
Hi Mario,
Thank you! 
So obvious after you pointed to the cause.
