### ISSUE TITLE
Add support of LiveData<> for async data querying

### ISSUE THREAD

**Issue by kzotin** [contentful/vault#131]
Since Android Arch components are becoming mainstream, it would be nice to add OOTB `LiveData<>` support for queries.

Currently we're wrapping RxJava calls with: `LiveDataReactiveStreams.fromPublisher(vault.observe(XYZ.class)...)`

PS. It would be also nice to extract RxJava to separate extension - like Room arch component is doing.

**Comment by mariobodemann** [comment]
Hey @kzotin,

those are great ideas. I will put it on our agenda and see when we get to it ... :) Thanks for your suggestions :+1:

**Comment by ashenriques** [comment]
Is this still on the agenda/pipeline? Now more than ever LiveData is mainstream, and this would be really nice to have.

**Comment by mariobodemann** [comment]
Hey,

so far we haven't made any progress on this topic, and I am not foreseeing us implementing it soon™.

Like always: If you feel you can contribute, I am happy to review any PRs.
