### ISSUE TITLE
How to do fuzzy & quick queries? (Proposal: Add full text search (FTS4) support to Vault)

### ISSUE THREAD

**Issue by kzotin** [contentful/vault#132]
Hi,

Thank you for hard work on Vault :) I've got 2 topics today:

1) Question

Our App relies heavily on search, and I'm currently investigating how to do search on the content inside Vault - both faster & with approximate text matching. 
Ideally it would be full-text search support of SQite, but I don't see an easy way of integrating it.
Could you advise please, what may be the viable & easy to implement option?

2) Proposal

It would be nice to add fuzzy search support to Vault (based on SQLite FTS4). It will be a killer feature!
Solution may be something like:
 * Annotate @searchable resource and @indexable fields
 * If Resource is @Searchable - together with regular tables, `$$ModelHelper` creates virtual FTS4 tables with @indexed fields
 * Populate FTS tables together with regular ones
 * Expose special MATCH query

Good post on FTS3/4:
https://stackoverflow.com/questions/29815248/full-text-search-example-in-android

Thanks in advance!

**Comment by mariobodemann** [comment]
Hey @kzotin,

thanks for the ongoing love with our SDKs!

We are evaluating current next steps with Vault and are happy to think about a full text feature. Sadly we are to early in the planing to commit to any features or even timelines, so I can only say thank you and we'll keep you informed.

Once more: Thank you for you valuable feedback, it is highly appreciated!

Greetings,
Mario

**Comment by kzotin** [comment]
Hey Mario,
Maybe you have any ideas (dirty hacks, etc.) how to improve search experience?
Thanks )

**Comment by mariobodemann** [comment]
< closing inactive ticket: No work is planned on this feature >
