### ISSUE TITLE
How to map DateTime & Reference to the @Field properly

### ISSUE THREAD

**Issue by kzotin** [contentful/vault#133]
Hi folks,

Can you please advise on simple question, how to map to map properly (haven't found such details in readme):
1) What java data type use for  `DateTime` field?

2) We have `Many references` field, which accepts various data types. 
Should I set `@Field List<Resource>` and find out instance type during runtime?

Thanks in advance! ;)

**Comment by kzotin** [comment]
awesome, thanks

**Comment by mariobodemann** [comment]
You are very welcome ....
