### ISSUE TITLE
Assets sync with multiple locales defined in space

### ISSUE THREAD

**Issue by bizon91** [contentful/vault#135]
Hi, 
when trying to synchronize contenful data with device i got following exception:

`com.contentful.vault.SyncException: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: assets$nb-NO.mime_type (code 1299)`

The reason is, it tries to insert media which has only one translation set (sv-SE) into two tables (assets$sv-SE and assets$nb-NO) setting some values as null for assets$nb-NO table (including mime_type which cannot be NULL).
Is it desired behavior ? If so, how to handle that ?

**Comment by mariobodemann** [comment]
Hello @bizon91,

I tried to reproduce your error and could only come to the same result, if the _default locale_ was _not having an asset_. If an non default asset was omitted, I did not receive this error. What is the setup of your locales? May `nb-NO` be your default one?

Can you double check, that you are having at least an asset set for the default locale?

Alternatively you could have the `reference`, which links your asset, be selected by the locale: set it to not existent, if you don't want it to be resolved. This essentially moves the responsibility one level up, from the asset to the reference, but you need to make sure that the reference field is not _required_ (cannot be empty)...

Greetings, and please let me know if you need further assistance.

Mario

**Comment by bizon91** [comment]
Hi, thanks for response.
Unfortunately default language suggestion doesn't help me because my default locale is sv-SE.

Moreover when checking Vault code, it seems as it doesn't distinguish between default or non default locale but tries to add asset into all locales I defined in space.

`@TargetApi(Build.VERSION_CODES.FROYO)
  private void saveAsset(CDAAsset asset) {
    AutoEscapeValues values = new AutoEscapeValues();
    for (String code : spaceHelper.getLocales()) {
      asset.setLocale(code);
      putResourceFields(asset, values);
      values.put(Asset.Fields.URL, "http:" + asset.url());
      values.put(Asset.Fields.MIME_TYPE, asset.mimeType());
      values.put(Asset.Fields.TITLE, asset.title());
      values.put(Asset.Fields.DESCRIPTION, asset.<String>getField("description"));

      byte[] value = null;
      Serializable fileMap = asset.getField("file");
      if (fileMap != null) {
        try {
          value = BlobUtils.toBlob(fileMap);
        } catch (IOException e) {
          throw new RuntimeException(
              String.format("Failed converting field map for asset with id '%s'.", asset.id()));
        }
      }
      values.put(Asset.Fields.FILE, value);

      db.insertWithOnConflict(escape(localizeName(TABLE_ASSETS, code)), null, values.get(),
          CONFLICT_REPLACE);

      values.clear();
    }
  }`

It is Vault - version 3.0.2.

If I'm correct, it looks like it iterates through all locales (spaceHelper.getLocales()) and tries to save asset into all tables and I haven't noticed any default/non default locale checking there.

**Comment by mariobodemann** [comment]
Hey,

I can see right now one way of mitigation: Set a fallback locale for the locale returning null right now: make `nb-NO` fallback to `sv-SE`. (WebApp: https://app.contentful.com/spaces/{YOUR_SPACE_ID}/settings/locales)

I hope that helps,
Mario

**Comment by bizon91** [comment]
When, setting fallback locale, to sv-SE (default one) it works, thanks.

**Comment by bizon91** [comment]
Hi, got one more question regarding that issue.
I'd like to have some entities only in one language and don't wan't to retrieve fallback language entity when no language for particular entity.
Is it possible to achieve using vault ?

**Comment by mariobodemann** [comment]
Hey @bizon91,

sadly the localization is set on content type level, so you can say a field inside a content type can be localized, but sadly not define it on a content type level. You could add dummy values you the entries where you don't want a translation, but turning off localization for specific entries is not possible.

Greetings,
Mario
