### ISSUE TITLE
Communication with Android 4.1.2 - SSL handshake aborted

### ISSUE THREAD

**Issue by hlandim** [contentful/vault#137]
Hello,
I'm passing through a problem when i request a sync my contents in a Android 4.1.2 device.

This is my code: 

> 
```
vault.requestSync(SyncConfig.builder()
                .setClient(client)
                .build(), new SyncCallback() {
            @Override
            public void onResult(SyncResult syncResult) {
                if (syncResult.isSuccessful()) {
                     ...
                }
                onNext.call(syncResult);
            }
        });
```

`syncResult.isSuccessful()` is `false` with `erro` :
>
```
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5c039588: Failure in SSL library, usually a protocol error
                                                                    error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x56e4b76a:0x00000000)
```

After some searching i found two links:
https://www.contentfulstatus.com/incidents/1svf18qn64qy
and 
https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han

Exist some fix to that?

**Comment by mariobodemann** [comment]
Hello,

This might be due to our upgrade to TLS 1.2 in the server side. Especially Android versions before 5 will benefit from the latest version of Vault (3.1.0) since it integrates the newest Contentful client, taking automatically care of the TLS issue.

Can you try and see if you are using this version?

**Comment by mariobodemann** [comment]
Hey @hlandim,

did updating the library help you at all?

Greetings, 
Mario

**Comment by hlandim** [comment]
Hey @mariobodemann 
Thanks for your response.
I fixed it with **useTLS12** method, like:

```
client = CDAClient.builder()
                .setSpace(Contentful.SPACE_ID)
                .setToken(Contentful.apiKey)
                .useTLS12()
                .build();
```
After that, all works fine.
Thanks.
