### ISSUE TITLE
Vault fails to sync in preview mode if there is an empty CDAAsset

### ISSUE THREAD

**Issue by chauhanmahesh** [contentful/vault#145]
com.contentful.vault.SyncException: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference

This exception is thrown when I try to sync vault in preview mode and there is a draft asset which is empty.

I create CDAClient for preview mode like this
CDAClient.builder().preview().setSpace(spaceType.spaceId).setToken(spaceType.getToken()).build()

It works as expected if there is no empty draft asset but fails if there is any.

**Comment by mariobodemann** [comment]
Hey,

sorry to hear about that exception. Do you mind sharing the full stacktrace? This way we can faster figure out were the problem lays...

Thanks you,
Mario

**Comment by chauhanmahesh** [comment]
Hi Mario,
Thanks for replying. Just to give you a context, this doesn't crashes the app vault gives the exception in its callback onResult(). This is the code:
```
vault.requestSync(syncConfigBuilder.build(), object : SyncCallback() {
            override fun onResult(result: SyncResult) {
                if(result.isSuccessful) {
                    syncCallback.onSuccess(null)
                } else {
                    Crashlytics.logException(result.error())
                    syncCallback.onFailure(AppStatusCode.FAILURE)
                }
            }
        })
```

So in the SyncResult object passed, I can see the exception. Also, the error which I mentioned in the original post is coming with latest vault version (v3.2.0). I was checking whether I can reproduce the exception in the latest version or not.
However, we are using v3.0.1 and the error is kind of different but I am sure the cause is still same 

"com.contentful.vault.SyncException: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: assets$en-US.mime_type (code 1299)"

![screen shot 2018-05-28 at 9 28 58 am](https://user-images.githubusercontent.com/361963/40591743-144a7580-625a-11e8-8463-667654ddd9bc.png)

**Comment by mariobodemann** [comment]
Hey,

thanks for the provided information, I will investigate, how to mitigate this issue.

Greetings,
Mario

**Comment by mariobodemann** [comment]
hey @chauhanmahesh,

I just released a bug fix for this issue: https://github.com/contentful/vault/releases/tag/v3.2.1 feel free to check it out and report back if it helps you.

Greetings,
Mario

**Comment by chauhanmahesh** [comment]
Hi @mariobodemann ,

I just checked with v3.2.1 and I can confirm that it's fixed 👍 
Thanks a lot for your quick action, really appreciate that.

Cheers
