### ISSUE TITLE
Kotin data class support

### ISSUE THREAD

**Issue by dbacinski** [contentful/vault#147]
To use Kotlin data classes I have to declare them as:

```
@ContentType("contactDetail")`
data class ContactDetail(
    @JvmField @Field var type: String = "",
    @JvmField @Field var text: String = ""
) : Resource()
```

Would be great to:
1. remove no-arg constructor requirement
2. remove public field requirement
3. add support for immutable fields without setter

With those requirements fulfilled we would be able to declare immutable data class like this:
```
@ContentType("contactDetail")`
data class ContactDetail(
    @Field val type: String,
    @Field val text: String
) : Resource()
```

**Comment by mariobodemann** [comment]
Hello,

sorry for the incredible delay, in case you are still interested, I'm coming back with bad news: Right now we have no plans on supporting data classes.

Greetings,
Mario
