### ISSUE TITLE
How can I get Location fields with Vault?

### ISSUE THREAD

**Issue by imecstamas** [contentful/vault#150]
In the contentful web app we are using a Location which I can't get it to work on Android with Vault. There is no such model for it as for the Asset for example. 
How can I get it work? 
Thanks,
Tamas

**Comment by mariobodemann** [comment]
Hey,

a location is a simple `Map` with `loc` and `lat` as keys. We will add this to our backlog, to try and avoid to have untyped maps anywhere, but for now we `Map` is the answer.

Greetings,
Mario

**Comment by mariobodemann** [comment]
https://github.com/contentful/vault/blob/master/tests-integration/src/test/java/com/contentful/vaultintegration/lib/allthethings/AllTheThingsResource.java#L22

See above link for the definition in the test cases.

**Comment by imecstamas** [comment]
Thank you very much, it's working!
