### ISSUE TITLE
Fetching entry without subentries

### ISSUE THREAD

**Issue by bizon91** [contentful/vault#152]
Hi,
I got resource A which contains list of resource B which contains list of resource C. I'd like to display list of A on screen but query takes a while since it also fetches related subitems. Is it possible to limit it somehow in vault by fetching entries without relations or by defining depth of resolving links.

**Comment by mariobodemann** [comment]
Hello,

sadly this is not possible: Vault will always fetch all the content from Contentful.

Greetings,
Mario
