### ISSUE TITLE
Rich text fields

### ISSUE THREAD

**Issue by quido3** [contentful/vault#156]
Is Rich Text fields possible with Vault? I have not found any documentation regarding it and it seems that the implementation is not compatible with any of the Rich Text classes provided in the main implementation of Contentful.

I am currently syncing the fields as String. It's working and seems to have all the data in it as text, but I don't know what I could do with the String.

**Comment by ZardozSpeaks** [comment]
According to the support person I talked with, it isn't currently possible with Vault. 

I wasn't even able to find an easy way to persist RichText using the standard SDK. It appears that some of the internal objects don't implement serializable so it isn't really possible to easily map a string representation back to an object. I ultimately wasn't able to find a solution that didn't involve writing to a file and a lot of reflection into the RichTextFactory class to get the object back in a usable form.

**Comment by quido3** [comment]
I solved this in one way. You can persist the Rich Text as a String. The
String will be in a weird form, but it's possible to convert that back into
a RichTextDocument. This rrequires a fork to get public access to the Rich
Text classes.
