### ISSUE TITLE
Asset metadata is incomplete

### ISSUE THREAD

**Issue by tomxor** [contentful/vault#46]
Currently only the URL and mime-type of an asset are provided by the `Asset` class. `title` should also be supported as well as the `file` JSON element and `description`.

**Comment by barteo** [comment]
Is it possible to get the data for the Asset as well? My goal is to access Asset content in app offline mode.

**Comment by tomxor** [comment]
By data you mean the actual file contents?

**Comment by barteo** [comment]
Yes, exactly.

**Comment by tomxor** [comment]
@barteo this is somewhat outside the scope of the library. You could use a `SyncCallback` to get notified once the data was made available, and then query using a combination of `updated_at` and `created_at` to get the delta from the last sync.
