### ISSUE TITLE
Proguard rules for vault

### ISSUE THREAD

**Issue by barteo** [contentful/vault#47]
What are the Proguard rules to embed vault into own application?

**Comment by tomxor** [comment]
This is a first attempt at this, since I normally don't use ProGuard, so please make sure to test your application properly and possibly provide some feedback about this configuration. In general, I use [android-proguard-snippets](https://github.com/krschultz/android-proguard-snippets) for external libraries, so any non-vault stuff in the following configuration file is derived from there.

```
# Vault
-keepattributes Signature
-dontwarn javax.lang.model.type.TypeMirror
-keep class com.contentful.vault.** { *; }
-keep class **$$SpaceHelper { *; }
-keep class **$$ModelHelper { *; }
-keep @com.contentful.vault.ContentType class * { *; }
-keep @com.contentful.vault.Space class * { *; }

# RxJava
-dontwarn rx.**

# OkHttp
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**


# Retrofit
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}

# Okio
-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**

# Gson
-keepattributes EnclosingMethod
-keep class com.google.gson.stream.** { *; }
```

**Comment by barteo** [comment]
Thanks for the detailed information.

I had to add additional rule to deal with large number of warnings:
-dontwarn javax.annotation.**

but I still get the following warning:
Warning: com.contentful.vault.compiler.Processor: can't find referenced field 'javax.annotation.processing.ProcessingEnvironment processingEnv' in program class com.contentful.vault.compiler.Processor

My application works fine, but I only tested it with -dontobfuscate Proguard option.

**Comment by tomxor** [comment]
This warning is also safe to ignore, as this class is only used at compile time. Can you please check if this makes it go away:
```
-dontwarn com.contentful.vault.compiler.**
```

Thanks!

**Comment by barteo** [comment]
Yes, this helped to remove this warning.

I've got another one, it doesn't come strictly from Vault, but from one of the dependencies:
com.squareup.javapoet.JavaFile: can't find referenced method 'java.nio.file.Path toPath()' in library class java.io.File

**Comment by tomxor** [comment]
JavaPoet is one of the dependencies (also used at compile-time). I'm wondering though why you get these warning and when I tested it I dind't, can you maybe post the entire proguard configuration file you're using?

**Comment by barteo** [comment]
Sure, this however includes some other Proguard rules for my app dependencies:
```
-dontobfuscate
-ignorewarnings
-keep class in.uncod.android.bypass.** { *; }

# Vault
-keepattributes Signature
-dontwarn javax.lang.model.type.TypeMirror
-dontwarn com.contentful.vault.compiler.**
-keep class com.contentful.vault.** { *; }
-keep class **$$SpaceHelper { *; }
-keep class **$$ModelHelper { *; }
-keep @com.contentful.vault.ContentType class * { *; }
-keep @com.contentful.vault.Space class * { *; }

# RxJava
-dontwarn rx.**

# OkHttp
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**

# Retrofit
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}

# Okio
-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**

# Gson
-keepattributes EnclosingMethod
-keep class com.google.gson.stream.** { *; }

# Squareup Javapoet TODO verify
-dontwarn java.nio.file.**

# Spullara Mustache TODO verify
-dontwarn org.jruby.**

# Others TODO verify
-dontwarn java.beans.**
-dontwarn javax.annotation.**
-dontwarn javax.lang.model.**
-dontwarn javax.tools.**
-dontwarn com.sun.tools.javac.code.**
-dontwarn sun.misc.Unsafe
```

**Comment by tomxor** [comment]
That seems pretty straightforward, can you also check which version of ProGuard you have?
```
java -jar /path-to-android-sdk/tools/proguard/lib/proguard.jar 
```

**Comment by barteo** [comment]
ProGuard, version 4.7

**Comment by tomxor** [comment]
Similar to other annotation processor libraries, the `com.contentful.vault:compiler` artifact is not required at runtime. I'm assuming you are declaring vault's dependencies like this:
```groovy
compile 'com.contentful.vault:core:VERSION'
compile 'com.contentful.vault:compiler:VERSION'
```

This actually results in the compiler artifact being bundled into the final APK and that is why ProGuard tries to optimize/obfuscate it as well. 

A better way of dealing with this is by using the [android-apt](https://bitbucket.org/hvisser/android-apt) gradle plugin, which allows you to define compile-time only dependencies, and also increases visibility for the generated code inside IntelliJ / Android Studio.

After you set up the plugin, declare the dependencies like this:
```groovy
apt 'com.contentful.vault:compiler:VERSION'
compile 'com.contentful.vault:core:VERSION'
```

And then you can use the original ProGuard configuration I've posted.

**Comment by tomxor** [comment]
(and that's also my fault since that's the way it is written in the README file :scream:)

**Comment by barteo** [comment]
Now, it builds correctly without -dontwarn com.contentful.vault.compiler.**

And final apk is a bit smaller :)

Thanks a lot.

**Comment by tomxor** [comment]
:+1: thank you for the feedback, I'll make sure to put a note into the README file.

**Comment by tomxor** [comment]
Actually one more rule is missing, for the contentful.java dependency:
```
# contentful.java
-keep class com.contentful.java.cda.** { *; }
```
