### ISSUE TITLE
RxJava support

### ISSUE THREAD

**Issue by tomxor** [contentful/vault#67]
Since links are represented on different tables this currently limits the query abilities when applying a `where()` clause, as one cannot add conditions based on linked entries:
```java
vault.fetch(Cat.class)
    .where("bestFriend.remote_id = ?", "foo") // won't work
    .all();
```
This forces the caller to filter the results manually. Among many other benefits, supporting queries with RxJava could make this a little bit less tedious, for example:
```java
vault.observe(Cat.class)
    .filter((cat) -> "FOO".equals(cat.bestFriend().remoteId())
    .subscribe((cat) -> ...);
```

**Comment by neonichu** [comment]
:+1:

**Comment by tomxor** [comment]
Still misses sync events via reactive stream.
