### ISSUE TITLE
Documentation on how to represent Links to other Entry types in models

### ISSUE THREAD

**Issue by davetao** [contentful/vault#70]
Would you be able to describe how we would represent Links to other resources in the model itself?
At the moment, we have a content type that references other entry types but do not know how to represent it in the data models.

Edit - to clarify, these links in the data model can refer to many different content types

**Comment by neonichu** [comment]
This is not possible with Vault. It is expected that a link field is strongly typed to only one content type, preferably by setting up [validations](https://www.contentful.com/r/knowledgebase/validations/#type) to ensure it.

Generally speaking, the easiest way to create Vault models for your Contentful content model is using our IntelliJ plugin, which can be found [here](https://plugins.jetbrains.com/plugin/7725?pr=idea_ce).

**Comment by tomxor** [comment]
As long as the list is typed to a specific `Resource` type (as mentioned above), you can define arrays of links like this:
```java
@Field List<Foo> foos;
@Field List<Asset> assets;
```

**Comment by davetao** [comment]
Thank you. It looks like our administrators have set up the links to point to many different types of resources instead of focusing on one. I will need to look to change their approach.

I have a few questions relating to the plugin, I will make a new issue on that project as my CMA token is not being accepted.

**Comment by davetao** [comment]
@tomxor just one last question to follow up the Links and references. Because the platform does allow you to choose to link to many different Content Types via validation, is there an approach we should use to manage this?

I imagine it makes the developer's life difficult when managing the relationships when using POJOs in this scenario

**Comment by neonichu** [comment]
You should select exactly one entry type for the "allowed entry type" validation in the content type editor. This ensures that editors cannot populate the link field with entries from other types.

<img width="670" alt="screen shot 2015-07-28 at 13 30 09" src="https://cloud.githubusercontent.com/assets/118992/8930263/d6790f08-352c-11e5-82c4-8ff89daced8e.png">

**Comment by davetao** [comment]
@neonichu thank you very much

**Comment by tomxor** [comment]
@davetao If you're experiencing any issues with the plugin please report here: https://github.com/contentful/cf-generator-intellij

Thanks!
