### ISSUE TITLE
NPE when an object has link references caused by predefined string values in model

### ISSUE THREAD

**Issue by davetao** [contentful/vault#79]
I was able to load up my content object using vault until I started added some links to other content types. It started to crash with the following stacktrace.

```
java.lang.NullPointerException
            at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:103)
            at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:70)
            at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:58)
            at com.contentful.vault.QueryResolver.resolveLinks(QueryResolver.java:81)
            at com.contentful.vault.QueryResolver.all(QueryResolver.java:65)
            at com.contentful.vault.FetchQuery.all(FetchQuery.java:27)
            at com.contentful.vault.FetchQuery.first(FetchQuery.java:31)
            at com.contentful.vault.FetchQuery.first(FetchQuery.java:43)
```

What else do you need to know to debug this scenario?

**Comment by tomxor** [comment]
Is it possible that you have links to different types of entries under the same field?

**Comment by davetao** [comment]
I have isolated it down to the sub model itself. Somehow the ORM links doesn't play well with pre defined string values.

````
{
  "name": "Content",
  "description": "Used for all content types",
  "displayField": "subtitle",
  "fields": [
    ...
    {
      "name": "Content Type",
      "id": "contentType",
      "type": "Symbol",
      "validations": [
        {
          "in": [
            "Audio",
            "Audio Slideshow",
            "Video",
            "Object Rotation",
            "Touch and Listen",
            "Text",
            "Text and image"
          ]
        }
      ]
    ...

````

**Comment by tomxor** [comment]
Hey David,

I don't think this is related to pre-defined strings, as the error indicates that the library is unable to find one of the generated classes for a specific linked resource. Is it possible that you've changed some models, while already having persisted data and without increasing the `dbVersion` value? if you're not sure, try increasing it anyway and see if the error reproduces.

Otherwise I would require your CDA credentials and model classes so I can try and reproduce this issue.

**Comment by davetao** [comment]
From what i can see, it appears that `contentType` is a reserved attribute used by Resource. That is very likely the cause of the issue.

**Comment by tomxor** [comment]
I am not sure if I completely understand, what do you mean by reserved attribute? in what way? can you provide a failing test case / example?

**Comment by davetao** [comment]
It was a user error on my behalf. I had a Content model that extended `Resource`. Which had `contentType` already. 
````
public abstract class Resource {
  String remoteId;
  String createdAt;
  String updatedAt;
  String contentType;
````
I would not be able to understand why it would cause a NPE though.

**Comment by tomxor** [comment]
The `contentType` attribute is set manually by the library, if you were to define it like this:
```java
@Field("contentType") String foo;
```

I believe it should be fine.

Thanks for the info.
